PermSetAssigner/objects/PermSetProfileAssignment__c/PermSetProfileAssignment__c.object-meta.xml
<CustomObject>
    <description>Assign a profile to a permission set</description>
    <label>Perm. Set Profile Assignment</label>
    <nameField>
        <displayFormat>PSA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Perm. Set Profile Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PermSetAssigner/objects/PermSetProfileAssignment__c/fields/PermissionSets__c.field-meta.xml
<CustomField>
    <fullName>PermissionSets__c</fullName>
    <description>Comma separated list of permission sets to assign to profile</description>
    <label>Permission Sets</label>
    <type>TextArea</type>
</CustomField>

PermSetAssigner/objects/PermSetProfileAssignment__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <description>Profile Name</description>
    <label>Profile</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/PermSetAssigner/objects/PSAssignment__mdt/PSAssignment__mdt.object-meta.xml
<CustomObject>
    <description>Assigns de permission set / permission set groups to profiles.
If a permission set (group) is defined here and not assigned to a profile, it will be removed when a user is affected to this profile</description>
    <label>PSAssignment</label>
    <pluralLabel>PSAssignments</pluralLabel>
</CustomObject>

force-app/PermSetAssigner/objects/PSAssignment__mdt/fields/PermissionSets__c.field-meta.xml
<CustomField>
    <fullName>PermissionSets__c</fullName>
    <description>Name of the permission set to affect</description>
    <label>Permission Sets</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

PermSetAssigner/objects/PSAssignment__mdt/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <description>Profiles to which the permission set should be affected (comma separated)</description>
    <label>Profile</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PermSetAssigner/classes/PSAConfigReader.cls
/**
 * @description       : 
 * @author            : VISEO / FFI
 * @last modified on  : 01-18-2024
 * @last modified by  : VISEO / FFI
**/
public with sharing class PSAConfigReader {

    private static Map<String, Set<String>> mapAssignments = new Map<String, Set<String>>();

    public static Map<String, Set<String>> read() {
        readConfFromCMDT();
        readConfFromData();
        return mapAssignments;

    }

    private static void readConfFromCMDT() {

        for(PSAssignment__mdt assignment : PSAssignment__mdt.getAll().Values()) {
            addAssignmentDataToMap(assignment.Profile__c, assignment.PermissionSets__c);
        }
        if(Test.isRunningTest()) {
            mapAssignments.clear();
            // For tests, only use test provided data (no custom metadata)
        }
    }

    private static void readConfFromData() {

        for(PermSetProfileAssignment__c assignment : [
            SELECT Profile__c, PermissionSets__c
            FROM PermSetProfileAssignment__c
            WITH SYSTEM_MODE
        ]) 
        {
            addAssignmentDataToMap(assignment.Profile__c, assignment.PermissionSets__c);
        }
    }
    
    private static void addAssignmentDataToMap(String profileName, String permissionSets) {
        String profId = PSAProfiles.profIds.get(profileName);
        List<String> lstPermSetIds = new list<String>();

        for(String psName : permissionSets.split(',')) {
            if(PSAProfiles.psIds.containsKey(psName)) {
                lstPermSetIds.add(PSAProfiles.psIds.get(psName));
            }
        }

        if(!mapAssignments.containsKey(profId)) {
            mapAssignments.put(profId, new Set<String>());
        }
        mapAssignments.get(profId).addAll(lstPermSetIds);
    }
}